name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - develop

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup .NET SDK 🔧
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Install wasm-tools 🛠️
        run: dotnet workload install wasm-tools

      - name: Publish Blazor WebAssembly 🔨
        run: |
          dotnet publish Anna_s_studio/Anna_s_studio.csproj -c Release -o release

      - name: Fix base href for GitHub Pages
        run: sed -i 's|<base href="/" />|<base href="/Anna_s_studio/" />|g' release/wwwroot/Anna_s_studio/index.html

      - name: Copy 404.html & .nojekyll 📄
        run: |
          cp release/wwwroot/Anna_s_studio/index.html release/wwwroot/Anna_s_studio/404.html
          touch release/wwwroot/Anna_s_studio/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: release/wwwroot/Anna_s_studio
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
